### ISSUE TITLE
Not working in Pd Extended (42-5) or Vanilla (47-1) 32 bits mac os 10.12.1

### ISSUE THREAD

**Issue by porres** [ericlyon/pd-fftease#14] opened 2016-12-01 18:01 UTC
I also dont see a 64 bit version to test

**Comment by ericlyon** [comment] 2016-12-01 21:17
The 64-bit versions are not developed yet, since Pd 64-bit still does its audio processing in 32-bit floating point. 32-bit FFTease works fine for me on Mac OS 10.12, using Pd 0.47.1. You could always recompile the objects on your own system to hopefully get them to work.

**Comment by porres** [comment] 2017-01-16 16:22
I know pd isn't internally in 64 bits, but I'm talking about making the library available for vanilla users who use the vanilla 64 but version. And, by the way, this library is available in Purr Data, and that distribution is in 64 bits, so ecven though this is still a 32 bit processing library, it can be made available for Pd 64 bits.
cheers

**Comment by ericlyon** [comment] 2017-01-16 18:08
I'm quite happy for others to make FFTease available for 64-bit Pd variants. Purr Data is a great example of that. Since the library is open source, anyone is welcome to make their own deployments.

**Comment by porres** [comment] 2020-11-24 22:14
I don't know how to make it available for Pd compiled for 64 bits (just to make a clear distinction here, I'm not talking about double precision). One way or another, I was testing this on the Pd 32 bit variant of Pd and also extended (which is only 32 bits) and it wasn't working.

Not that I care anymore as I'm now only using Pd compiled for 64 bit processors (again, not double precision). So I'm now more concerned on how to compile and get this working for 64 bit processors. I'm also having problems with that, even though Purr Data carries a working version of FFTease for 64 bits.

Anyway, since this is working in Purr Data, I was hoping it would also work in Vanilla and I can help uploading it to deken so people can easily download and use this library in Vanilla. But I should discuss the issue compiling and getting it to work in 64 in https://github.com/ericlyon/fftease3.0-32bit/issues/15

**Comment by ericlyon** [comment] 2020-11-24 22:34
Yes, I understand. IIRC I successfully compiled the externals for Pd for
64-bit processors. I think the issue was that Miller had introduced a new
way of accessing arrays, and discontinued an older function call. Anyway,
I'm pretty sure the distro I shared has the code updates. At least I had it
working on Mac OS at one point.

Best,
Eric

**Comment by umlaeute** [comment] 2021-01-12 14:53
it seems that this discussion disgressed into a duplicate of #15 .

however: what about the original issue which is:
> Not working in Pd Extended (42-5) or Vanilla (47-1) 32 bits mac os 10.12.1

???

**Comment by ericlyon** [comment] 2021-01-12 14:56
> it seems that this discussion disgressed into a duplicate of #15 .
> 
> however: what about the original issue which is:
> 
> > Not working in Pd Extended (42-5) or Vanilla (47-1) 32 bits mac os 10.12.1
> 
> ???

Maybe this issue should be closed?

**Comment by umlaeute** [comment] 2021-01-12 15:32
@porres ^^^

**Closed** 2021-01-12 16:10 UTC
